parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        roofikk\AvestaBundle\Contracts\ApiClientInterface:
            tags: [ 'roofikk.avesta.client' ]

    roofikk\AvestaBundle\Manager\AvestaClientManager:
        arguments:
            $testVar: 'Hello from yaml'